name: eduaction_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  intl_phone_field: ^3.2.0

flutter_native_splash:
  image: 'assets/icons/app_icon.png'
  android: true
  ios: true
  color: "#FFFFFF"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Cairo/
    - assets/icons/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/choosespeclization/
    - assets/images/homeandother/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf